#nacosurl: 113.98.201.156:8848
#nacos: nacos://
#redisurl: 192.168.0.103
#redisport: 6379
#mysqlUrl: 192.168.0.103:3306
#isTest: true
#mysqlUser: root
#mysqlPwd: mugui123

host: 127.0.0.1
nacosurl: ${host}:8848
nacos: nacos://
redisurl: ${host}
mysqlUrl: rm-j6c3c72h35x0t15fp.mysql.rds.aliyuncs.com:3306
mysqlUser: mugui
mysqlPwd: Huangshen123

dbName: dg
server:
  port: 8074
redisRegion: 5
dubbo:
  cloud:
    subscribed-services: AuthorityServiceManagerApi
spring:
  application:
    name: GE_DraGonSwap
  profiles:
    include:
    - base
